using System;
using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyTitleAttribute("NHibernate.Shards")]
[assembly: AssemblyCompanyAttribute("nhforge.org")]
[assembly: AssemblyProductAttribute("NHibernate.Shards")]
[assembly: AssemblyCopyrightAttribute("Licensed under LGPL.")]
[assembly: AssemblyVersionAttribute("4.2.0.2000")]
[assembly: AssemblyFileVersionAttribute("4.2.0.2000")]
[assembly: AssemblyInformationalVersionAttribute("4.2.0.2000")]

