using System;
using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyTitleAttribute("NHibernate.Shards.Test")]
[assembly: AssemblyCompanyAttribute("nhforge.org")]
[assembly: AssemblyProductAttribute("NHibernate.Shards")]
[assembly: AssemblyCopyrightAttribute("Licensed under LGPL.")]
[assembly: AssemblyVersionAttribute("3.3.1.3001")]
[assembly: AssemblyFileVersionAttribute("3.3.1.3001")]
[assembly: AssemblyInformationalVersionAttribute("3.3.1.3001")]

